//! Level-1 node-face icons (v0.4.1) — a type/file-subtype glyph on **every**
//! visible node, drawn as a billboarded quad sampling one shared atlas.
//!
//! Cost is O(visible) and allocation-free in steady state: a single atlas
//! texture, one quad mesh per glyph cell (a fixed set, not per-node), and a
//! small per-kind material set — all shared across nodes (Bevy GPU-instances
//! entities with identical mesh+material). Icons are tier-independent (always on,
//! cheap), matching the v0.5.0 gate-glyph split (`docs/spec_v0.5.0.md` §2.3); on
//! `Low` they use a flat colour variant instead of the textured glyph.
//!
//! **v0.5.0 seam:** this face glyph is the *centre* of v0.5.0's gate-glyph unit
//! (WP-2: concentric ring + centre icon), and the centre that the radial command
//! HUD (WP-3) will wrap.

use std::collections::HashMap;

use bevy::prelude::*;
use bevy::render::mesh::{Indices, PrimitiveTopology};
use bevy::render::render_asset::RenderAssetUsages;
use bevy::render::render_resource::{Extent3d, TextureDimension, TextureFormat};
use bevy::render::texture::ImageSampler;
use spacegraph_core::{FileKind, Node};

use crate::graph::interner::NodeIndex;
use crate::graph::{GraphState, ViewMode};
use crate::render::capability::DetailCapability;
use crate::render::theme;
use crate::util::config::VisualTheme;

/// Committed atlas: raw RGBA8 (no Bevy image-format feature needed — loaded via
/// `Image::new`, not the asset loader). Generated by `assets/icons/gen_atlas.py`.
const ATLAS_BYTES: &[u8] = include_bytes!("../../assets/icons/atlas.rgba");
pub const ATLAS_SIZE: u32 = 256;
const ATLAS_COLS: u32 = 4;
const ICON_COUNT: usize = 15;
const KIND_COUNT: usize = theme::NodeKind::ALL.len();
/// Largest icon half-extent (world units) — the cap: an icon never exceeds the
/// old fixed size, and is clamped *down* to smaller nodes' envelopes below.
const ICON_HALF_MAX: f32 = 0.26;
/// Smallest icon half-extent so even the smallest cores show a legible glyph.
const ICON_HALF_MIN: f32 = 0.14;
/// Fraction of a node's core envelope the icon fills (< 1 so the glyph sits *on*
/// the node face rather than overhanging it as a block — the v0.5.1 bugfix).
const ICON_FILL: f32 = 0.9;
/// Offset of the icon from the node centre toward the camera (on the near face).
const ICON_OFFSET: f32 = 0.42;

/// A type/file-subtype glyph identity. Maps to an atlas cell; the order here is
/// the contract with `gen_atlas.py`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IconId {
    Process,
    User,
    Socket,
    RemoteHost,
    Alert,
    FileGeneric,
    FileImage,
    FileVideo,
    FileText,
    FileCode,
    FileJson,
    FileLog,
    FileAudio,
    FileArchive,
    FileBinary,
}

impl IconId {
    pub const ALL: [IconId; ICON_COUNT] = [
        IconId::Process,
        IconId::User,
        IconId::Socket,
        IconId::RemoteHost,
        IconId::Alert,
        IconId::FileGeneric,
        IconId::FileImage,
        IconId::FileVideo,
        IconId::FileText,
        IconId::FileCode,
        IconId::FileJson,
        IconId::FileLog,
        IconId::FileAudio,
        IconId::FileArchive,
        IconId::FileBinary,
    ];

    /// Atlas cell index (row-major in the 4×4 grid).
    pub fn cell(self) -> u32 {
        match self {
            IconId::Process => 0,
            IconId::User => 1,
            IconId::Socket => 2,
            IconId::RemoteHost => 3,
            IconId::Alert => 4,
            IconId::FileGeneric => 5,
            IconId::FileImage => 6,
            IconId::FileVideo => 7,
            IconId::FileText => 8,
            IconId::FileCode => 9,
            IconId::FileJson => 10,
            IconId::FileLog => 11,
            IconId::FileAudio => 12,
            IconId::FileArchive => 13,
            IconId::FileBinary => 14,
        }
    }
}

/// Map a file path to its subtype glyph by extension (pure, unit-tested).
pub fn file_subtype(path: &str) -> IconId {
    let name = path.rsplit('/').next().unwrap_or(path);
    let ext = match name.rsplit_once('.') {
        Some((stem, e)) if !stem.is_empty() => e.to_ascii_lowercase(),
        _ => String::new(), // no extension / dotfile → generic
    };
    match ext.as_str() {
        "png" | "jpg" | "jpeg" | "gif" | "bmp" | "webp" | "svg" | "tiff" | "tif" | "ico" => {
            IconId::FileImage
        }
        "mp4" | "mkv" | "avi" | "mov" | "webm" | "flv" | "wmv" | "m4v" => IconId::FileVideo,
        "mp3" | "wav" | "flac" | "ogg" | "m4a" | "aac" | "opus" => IconId::FileAudio,
        "rs" | "py" | "js" | "ts" | "tsx" | "jsx" | "c" | "cc" | "cpp" | "h" | "hpp" | "go"
        | "java" | "rb" | "sh" | "bash" | "cs" | "php" | "swift" | "kt" | "lua" | "sql" => {
            IconId::FileCode
        }
        "json" | "yaml" | "yml" | "toml" | "xml" | "csv" | "ini" | "conf" => IconId::FileJson,
        "log" => IconId::FileLog,
        "txt" | "md" | "rst" | "text" | "rtf" => IconId::FileText,
        "zip" | "tar" | "gz" | "tgz" | "bz2" | "xz" | "7z" | "rar" | "zst" | "lz4" => {
            IconId::FileArchive
        }
        "exe" | "dll" | "so" | "bin" | "o" | "a" | "dylib" | "class" | "wasm" => IconId::FileBinary,
        _ => IconId::FileGeneric,
    }
}

/// Glyph for a node: type for non-files, extension subtype for files.
pub fn icon_for(node: &Node) -> IconId {
    match node {
        Node::Process { .. } => IconId::Process,
        Node::User { .. } => IconId::User,
        Node::Socket { .. } => IconId::Socket,
        Node::RemoteHost { .. } => IconId::RemoteHost,
        Node::Alert { .. } => IconId::Alert,
        Node::File { path, kind, .. } => match kind {
            FileKind::Dir => IconId::FileGeneric,
            _ => file_subtype(path),
        },
    }
}

/// Visual half-envelope of each node kind's core, mirroring the `render::node_mesh`
/// geometry sizes. Used to clamp the face-icon billboard to the node's scale.
fn node_envelope(kind: theme::NodeKind) -> f32 {
    match kind {
        theme::NodeKind::Process => 0.26,    // octahedron_solid(0.26)
        theme::NodeKind::File => 0.17,       // hex plate radius 0.17
        theme::NodeKind::User => 0.18,       // cone radius 0.18
        theme::NodeKind::Socket => 0.22,     // torus outer 0.22
        theme::NodeKind::RemoteHost => 0.30, // octahedron wire shell 0.30
        theme::NodeKind::Alert => 0.34,      // spiked-star shell 0.34
    }
}

/// Face-icon half-extent (world units) **clamped to the node's scale**: a fraction
/// of the kind's core envelope, bounded to `[ICON_HALF_MIN, ICON_HALF_MAX]`. Pure +
/// unit-tested. Guarantees the billboard never overhangs the node (the v0.5.1
/// "big block" bug) while staying legible on the smallest cores.
pub fn icon_half_extent(kind: theme::NodeKind) -> f32 {
    (node_envelope(kind) * ICON_FILL).clamp(ICON_HALF_MIN, ICON_HALF_MAX)
}

/// Marker on a node-face icon entity.
#[derive(Component)]
pub struct NodeIconMarker;

/// Back-reference from an icon entity to its node.
#[derive(Component)]
pub struct IconRef(pub NodeIndex);

/// Persistent icon entities, one per visible node (spawn on add, despawn on
/// remove — no per-frame churn).
#[derive(Resource, Default)]
pub struct NodeIcons {
    pub map: HashMap<NodeIndex, Entity>,
}

/// Shared icon render resources: a **single** atlas texture, a fixed quad-mesh
/// set (one per glyph cell), and per-kind materials. No per-node allocation.
#[derive(Resource)]
pub struct NodeIconResources {
    pub atlas: Handle<Image>,
    pub quad: [Handle<Mesh>; ICON_COUNT],
    /// Textured glyph materials (Mid/High) — all sample `atlas`.
    pub glyph_mat: [Handle<StandardMaterial>; KIND_COUNT],
    /// Flat colour materials (Low) — untextured "colour icon" variant.
    pub flat_mat: [Handle<StandardMaterial>; KIND_COUNT],
}

/// LDR, legible type tint (lifted toward white so the glyph reads on dark cores;
/// kept ≤ 1.0 so it does not bloom and stays crisp).
fn icon_tint(kind: theme::NodeKind) -> Color {
    let c = kind.base_color().to_srgba();
    Color::srgb(
        (c.red * 0.6 + 0.4).min(1.0),
        (c.green * 0.6 + 0.4).min(1.0),
        (c.blue * 0.6 + 0.4).min(1.0),
    )
}

/// UV rect of a cell (1-texel inset to avoid bleeding into neighbours).
fn cell_uv(cell: u32) -> (f32, f32, f32, f32) {
    let col = (cell % ATLAS_COLS) as f32;
    let row = (cell / ATLAS_COLS) as f32;
    let s = 1.0 / ATLAS_COLS as f32;
    let inset = 0.5 / ATLAS_SIZE as f32;
    (
        col * s + inset,
        (col + 1.0) * s - inset,
        row * s + inset,
        (row + 1.0) * s - inset,
    )
}

/// A camera-plane quad with the atlas UVs of `cell` baked in (the per-instance
/// glyph selection lives in the mesh, not the material — so all nodes share one
/// atlas + one material per kind, and Bevy instances them).
fn icon_quad_mesh(cell: u32) -> Mesh {
    // Unit quad (half-extent 1.0); the per-kind size is applied via the icon
    // entity's `Transform.scale` (`icon_half_extent`), so the billboard is clamped
    // to the node's scale rather than a fixed world size.
    let h = 1.0_f32;
    let (u0, u1, v0, v1) = cell_uv(cell);
    Mesh::new(
        PrimitiveTopology::TriangleList,
        RenderAssetUsages::default(),
    )
    .with_inserted_attribute(
        Mesh::ATTRIBUTE_POSITION,
        vec![[-h, h, 0.0], [h, h, 0.0], [h, -h, 0.0], [-h, -h, 0.0]],
    )
    .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, vec![[0.0, 0.0, 1.0]; 4])
    .with_inserted_attribute(
        Mesh::ATTRIBUTE_UV_0,
        vec![[u0, v0], [u1, v0], [u1, v1], [u0, v1]],
    )
    .with_inserted_indices(Indices::U32(vec![0, 1, 2, 0, 2, 3]))
}

/// Build the shared icon resources (atlas + quad set + materials).
fn build_icon_resources(
    meshes: &mut Assets<Mesh>,
    mats: &mut Assets<StandardMaterial>,
    images: &mut Assets<Image>,
) -> NodeIconResources {
    let mut atlas_img = Image::new(
        Extent3d {
            width: ATLAS_SIZE,
            height: ATLAS_SIZE,
            depth_or_array_layers: 1,
        },
        TextureDimension::D2,
        ATLAS_BYTES.to_vec(),
        TextureFormat::Rgba8UnormSrgb,
        RenderAssetUsages::RENDER_WORLD,
    );
    // Crisp alpha cutout (v0.5.1 bugfix): nearest sampling makes every fragment's
    // alpha exactly 0 or 1, so the opaque-pass alpha mask (`AlphaMode::Mask`) cuts
    // a clean glyph instead of a linearly-blended edge haze that can read as a
    // filled quad. (The atlas data is white-on-transparent; GPU confirmation is a
    // local step in this headless env.)
    atlas_img.sampler = ImageSampler::nearest();
    let atlas = images.add(atlas_img);
    let quad = std::array::from_fn(|i| meshes.add(icon_quad_mesh(IconId::ALL[i].cell())));
    let glyph_mat = std::array::from_fn(|i| {
        mats.add(StandardMaterial {
            base_color: icon_tint(theme::NodeKind::ALL[i]),
            base_color_texture: Some(atlas.clone()),
            unlit: true,
            // Alpha-mask keeps icons in the opaque pass (no per-frame transparency
            // sort / overdraw cost across thousands of nodes).
            alpha_mode: AlphaMode::Mask(0.5),
            cull_mode: None,
            ..default()
        })
    });
    let flat_mat = std::array::from_fn(|i| {
        mats.add(StandardMaterial {
            base_color: icon_tint(theme::NodeKind::ALL[i]),
            unlit: true,
            cull_mode: None,
            ..default()
        })
    });
    NodeIconResources {
        atlas,
        quad,
        glyph_mat,
        flat_mat,
    }
}

pub fn setup_node_icon_resources(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut mats: ResMut<Assets<StandardMaterial>>,
    mut images: ResMut<Assets<Image>>,
) {
    let res = build_icon_resources(&mut meshes, &mut mats, &mut images);
    commands.insert_resource(res);
}

/// Keep node-face icons in sync with the visible graph and billboard them to the
/// camera. Standard-theme + spatial + non-LOD only (mirrors `sync_node_entities`);
/// spawns on node-add, despawns on remove, otherwise mutates Transform/handles.
#[allow(clippy::type_complexity)]
pub fn sync_node_icons(
    mut commands: Commands,
    st: Res<GraphState>,
    res: Res<NodeIconResources>,
    cap: Res<DetailCapability>,
    mut icons: ResMut<NodeIcons>,
    cam_q: Query<&GlobalTransform, With<Camera>>,
    mut q: Query<
        (
            &mut Transform,
            &mut Handle<Mesh>,
            &mut Handle<StandardMaterial>,
        ),
        With<NodeIconMarker>,
    >,
) {
    let vis = &st.spatial.vis_cache;
    let icons_on = st.ui.view_mode == ViewMode::Spatial
        && !st.cfg.lod_active(vis.len())
        && st.cfg.visual_theme == VisualTheme::Standard;

    if !icons_on {
        if !icons.map.is_empty() {
            for (_, e) in icons.map.drain() {
                commands.entity(e).despawn_recursive();
            }
        }
        return;
    }

    let Ok(cam_tf) = cam_q.get_single() else {
        return;
    };
    let (_, cam_rot, cam_pos) = cam_tf.to_scale_rotation_translation();
    let low = *cap == DetailCapability::Low;

    // Despawn icons whose node left the visible set or is fogged.
    icons.map.retain(|&idx, &mut e| {
        let keep = st.spatial.index_visible(idx, vis)
            && st
                .spatial
                .interner
                .resolve(idx)
                .map(|id| st.is_visible_rendered(id))
                .unwrap_or(false);
        if !keep {
            commands.entity(e).despawn_recursive();
        }
        keep
    });

    for id in vis.iter() {
        let Some(idx) = st.spatial.index_of(id) else {
            continue;
        };
        if !st.spatial.placed[idx.slot()] || !st.is_visible_rendered(id) {
            continue;
        }
        let Some(node) = st.core.model.nodes.get(id) else {
            continue;
        };
        let kind = theme::NodeKind::of(node);
        let icon = icon_for(node);
        let pos = st.spatial.positions[idx.slot()];
        let icon_pos = pos + (cam_pos - pos).normalize_or_zero() * ICON_OFFSET;
        let scale = Vec3::splat(icon_half_extent(kind)); // clamp billboard to node scale
        let mesh = res.quad[icon.cell() as usize].clone();
        let material = if low {
            res.flat_mat[kind.index()].clone()
        } else {
            res.glyph_mat[kind.index()].clone()
        };

        if let Some(&e) = icons.map.get(&idx) {
            if let Ok((mut tf, mut mh, mut mat)) = q.get_mut(e) {
                tf.translation = icon_pos;
                tf.rotation = cam_rot; // screen-aligned billboard
                tf.scale = scale;
                if *mh != mesh {
                    *mh = mesh;
                }
                if *mat != material {
                    *mat = material;
                }
            }
        } else {
            let e = commands
                .spawn((
                    PbrBundle {
                        mesh,
                        material,
                        transform: Transform {
                            translation: icon_pos,
                            rotation: cam_rot,
                            scale,
                        },
                        ..default()
                    },
                    NodeIconMarker,
                    IconRef(idx),
                ))
                .id();
            icons.map.insert(idx, e);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::GraphState;

    fn graph_state(n: usize) -> GraphState {
        let mut gs = GraphState::default();
        gs.cfg.max_visible_nodes = n + 16;
        gs.cfg.progressive_nodes_per_frame = n + 16;
        gs.load_synthetic_graph(n);
        let vis = gs.visible_set_capped();
        gs.progressive_prepare(&vis);
        gs.spatial.vis_cache = vis;
        gs
    }

    fn dummy_icon_resources() -> NodeIconResources {
        NodeIconResources {
            atlas: Handle::weak_from_u128(7000),
            quad: std::array::from_fn(|i| Handle::weak_from_u128(7100 + i as u128)),
            glyph_mat: std::array::from_fn(|i| Handle::weak_from_u128(7200 + i as u128)),
            flat_mat: std::array::from_fn(|i| Handle::weak_from_u128(7300 + i as u128)),
        }
    }

    fn icon_entities(app: &mut App) -> std::collections::HashSet<Entity> {
        let mut q = app
            .world_mut()
            .query_filtered::<Entity, With<NodeIconMarker>>();
        q.iter(app.world()).collect()
    }

    fn spawn_camera(app: &mut App) {
        app.world_mut().spawn((
            Camera::default(),
            GlobalTransform::from_translation(Vec3::new(0.0, 0.0, 120.0)),
        ));
    }

    #[test]
    fn file_subtype_maps_extensions() {
        assert_eq!(file_subtype("/home/a/pic.PNG"), IconId::FileImage);
        assert_eq!(file_subtype("/v/clip.mp4"), IconId::FileVideo);
        assert_eq!(file_subtype("/m/song.flac"), IconId::FileAudio);
        assert_eq!(file_subtype("/src/main.rs"), IconId::FileCode);
        assert_eq!(file_subtype("/etc/app.json"), IconId::FileJson);
        assert_eq!(file_subtype("/var/log/sys.log"), IconId::FileLog);
        assert_eq!(file_subtype("/doc/readme.md"), IconId::FileText);
        assert_eq!(file_subtype("/a/backup.tar.gz"), IconId::FileArchive);
        assert_eq!(file_subtype("/usr/lib/libc.so"), IconId::FileBinary);
        // No extension and dotfiles → generic.
        assert_eq!(file_subtype("/etc/passwd"), IconId::FileGeneric);
        assert_eq!(file_subtype("/home/u/.bashrc"), IconId::FileGeneric);
    }

    #[test]
    fn icon_for_dispatches_node_kinds() {
        use spacegraph_core::Node;
        assert_eq!(
            icon_for(&Node::Process {
                pid: 1,
                ppid: 0,
                exe: "x".into(),
                cmdline: "x".into(),
                uid: 0
            }),
            IconId::Process
        );
        assert_eq!(
            icon_for(&Node::File {
                path: "/a/b.png".into(),
                inode: 1,
                kind: FileKind::Regular
            }),
            IconId::FileImage
        );
        // A directory is generic regardless of any extension-like name.
        assert_eq!(
            icon_for(&Node::File {
                path: "/a/b.png".into(),
                inode: 1,
                kind: FileKind::Dir
            }),
            IconId::FileGeneric
        );
    }

    #[test]
    fn atlas_alpha_is_a_cutout_mask() {
        // The committed atlas must be a real cutout: its alpha channel is bimodal —
        // fully-transparent background texels AND opaque glyph texels. With the
        // `AlphaMode::Mask` material below this guards that icons render a glyph
        // cutout, not a filled quad (the "big green block" bug). GPU confirmation is
        // a local step in this headless env.
        let alphas: Vec<u8> = ATLAS_BYTES.iter().skip(3).step_by(4).copied().collect();
        assert_eq!(alphas.len(), (ATLAS_SIZE * ATLAS_SIZE) as usize);
        let transparent = alphas.iter().filter(|&&a| a == 0).count();
        let opaque = alphas.iter().filter(|&&a| a == 255).count();
        assert!(
            transparent > 0,
            "atlas must have transparent background texels"
        );
        assert!(opaque > 0, "atlas must have opaque glyph texels");
        assert!(
            transparent > opaque,
            "glyph is a sparse cutout, not a filled block"
        );
    }

    #[test]
    fn glyph_material_is_alpha_masked_with_nearest_atlas() {
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, bevy::asset::AssetPlugin::default()))
            .init_asset::<Image>()
            .init_asset::<Mesh>()
            .init_asset::<StandardMaterial>()
            .add_systems(Startup, setup_node_icon_resources);
        app.update();

        let res = app.world().resource::<NodeIconResources>();
        let mats = app.world().resource::<Assets<StandardMaterial>>();
        let images = app.world().resource::<Assets<Image>>();
        // Every textured glyph material masks (opaque-pass cutout), not opaque fill.
        for h in res.glyph_mat.iter() {
            let m = mats.get(h).expect("glyph material present");
            assert!(
                matches!(m.alpha_mode, AlphaMode::Mask(_)),
                "glyph material must alpha-mask the cutout"
            );
        }
        // The atlas carries an explicit (nearest) sampler so the mask edge is crisp
        // (per-fragment alpha 0/1), not the linear default that blurs thin strokes.
        let atlas = images.get(&res.atlas).expect("atlas image present");
        assert!(
            matches!(atlas.sampler, ImageSampler::Descriptor(_)),
            "atlas must use an explicit sampler (nearest), not the linear default"
        );
    }

    #[test]
    fn icon_half_extent_is_clamped_to_node_scale() {
        for kind in theme::NodeKind::ALL {
            let h = icon_half_extent(kind);
            assert!(
                h <= ICON_HALF_MAX + f32::EPSILON,
                "{kind:?} exceeds the cap"
            );
            assert!(
                h >= ICON_HALF_MIN - f32::EPSILON,
                "{kind:?} too small to read"
            );
            // Never overhangs the node core (the "big block" bug).
            assert!(
                h <= node_envelope(kind) + 1e-4,
                "{kind:?} icon must fit within the node envelope"
            );
        }
        // A larger node carries a larger-or-equal glyph.
        assert!(
            icon_half_extent(theme::NodeKind::Alert) >= icon_half_extent(theme::NodeKind::File)
        );
    }

    #[test]
    fn icon_cells_are_unique_and_in_range() {
        let mut seen = std::collections::HashSet::new();
        for icon in IconId::ALL {
            let c = icon.cell();
            assert!(c < ICON_COUNT as u32);
            assert!(seen.insert(c), "duplicate atlas cell {c}");
        }
    }

    #[test]
    fn icons_share_one_atlas_and_quad_set() {
        // Structural perf proxy: a single atlas handle, and every textured glyph
        // material references that same handle (no per-node texture/material).
        let mut app = App::new();
        app.add_plugins((MinimalPlugins, bevy::asset::AssetPlugin::default()))
            .init_asset::<Image>()
            .init_asset::<Mesh>()
            .init_asset::<StandardMaterial>()
            .add_systems(Startup, setup_node_icon_resources);
        app.update();

        let res = app.world().resource::<NodeIconResources>();
        let mats = app.world().resource::<Assets<StandardMaterial>>();
        assert_eq!(res.quad.len(), ICON_COUNT);
        for h in res.glyph_mat.iter() {
            let m = mats.get(h).expect("glyph material present");
            assert_eq!(
                m.base_color_texture.as_ref(),
                Some(&res.atlas),
                "all glyph materials must share the single atlas handle"
            );
        }
        // Flat (Low) materials are untextured colour chips.
        for h in res.flat_mat.iter() {
            let m = mats.get(h).expect("flat material present");
            assert!(m.base_color_texture.is_none());
        }
    }

    #[test]
    fn spawns_one_icon_per_visible_node_in_standard() {
        let mut app = App::new();
        let gs = graph_state(120);
        let want = gs.spatial.vis_cache.len();
        app.insert_resource(gs)
            .insert_resource(NodeIcons::default())
            .insert_resource(dummy_icon_resources())
            .insert_resource(DetailCapability::Mid)
            .add_systems(Update, sync_node_icons);
        spawn_camera(&mut app);
        app.update();
        assert!(want > 0);
        assert_eq!(
            icon_entities(&mut app).len(),
            want,
            "one icon per visible node"
        );
    }

    #[test]
    fn minimal_theme_has_no_icons() {
        let mut app = App::new();
        let mut gs = graph_state(80);
        gs.cfg.visual_theme = VisualTheme::Minimal;
        app.insert_resource(gs)
            .insert_resource(NodeIcons::default())
            .insert_resource(dummy_icon_resources())
            .insert_resource(DetailCapability::Mid)
            .add_systems(Update, sync_node_icons);
        spawn_camera(&mut app);
        app.update();
        assert_eq!(icon_entities(&mut app).len(), 0, "Minimal draws no icons");
    }

    #[test]
    fn icons_have_no_steady_state_churn() {
        let mut app = App::new();
        app.insert_resource(graph_state(150))
            .insert_resource(NodeIcons::default())
            .insert_resource(dummy_icon_resources())
            .insert_resource(DetailCapability::Mid)
            .add_systems(Update, sync_node_icons);
        spawn_camera(&mut app);

        app.update();
        let frame1 = icon_entities(&mut app);
        assert!(!frame1.is_empty());
        app.update();
        let frame2 = icon_entities(&mut app);
        assert_eq!(frame1, frame2, "steady state must not respawn icons");
    }
}
